name: Build and Test

on:
  push:
    branches:
      - master
      - dev

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [16.x, 18.x]
        npm-client: [npm, yarn, pnpm]

    steps:
      - uses: pnpm/action-setup@v2
        if: matrix.npm-client == 'pnpm'
        name: Install pnpm
        with:
          version: 7
          run_install: false

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: ${{ matrix.npm-client }} install

      - name: Build
        run: ${{ matrix.npm-client }} run build